permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 10 #6
comments: false
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Wikimo's Note
description: "me.each do |devel| … !end."
email: gwikimo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://wikimo.net"
repository: "https://github.com/wikimo"
disqus_shortname:
google_analytics: 
cname: 'wikimo.net'

# social footer
social:
  github:
    slug: github
    link: http://github.com/wikimo
  # facebook:
  #   slug: facebook
  #   link: 
  twitter:
    slug: twitter
    link: http://twitter.com/gwikimo